### ISSUE TITLE
Write up is well documented, but needs actual code and conversion to .md

### ISSUE THREAD

**Issue by DCGenomics** [Whitcomb-Lab/GWAS-Analysis-Pipeline#1]
@BMBlobner -- please:

commit the actual commands you described in some sort of script (bash, perhaps?) 

Convert the writeup from word to markdown and commit on the README.md?

Text or email me if you need help?

**Comment by BMBlobner** [comment]
The writeup has been converted to markdown.
The commands used can be found in the following files:
- stepwise_regression.R contains the R script for fitting the linear model and performing stepwise regression using stepAIC from the 'MASS' package.
- make_grm.sh contains the command and options used to generate a GRM using GCTA.
- make_pca.sh contains the command and options used to generate PCAs from the GRM generated using make_grm.sh and GCTA.
-GWAS_script.sh contains the command and options used to perform a GWAS using GCTA.
